# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     service: mongodb
#   name: mongodb
# spec:
#   ports:
#   - name: mongo
#     port: 27017
#     targetPort: 27017
#   selector:
#     service: mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
   